---
abstract: "API Modules for RabbitMQ clusters' API"
author:
  - 'Shane Utt (shane@shaneutt.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-RabbitMQ-Cluster
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 6
  JSON: 2.9
  LWP::UserAgent: 6.04
  Test::Simple: 0.44
  URI: 1.6
  Want: 0.23
version: 0.01
